# Generated by Django 2.1.4 on 2019-01-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(related_name='students', to='more_table.Student'),
        ),
    ]
